//DROP ALL OBJECTS DELETE FILES;
create table if not exists users
(
    user_id  bigint generated by default as identity primary key,
    email    character varying(255),
    login    character varying(255),
    name     character varying(1000),
    birthday date,
    constraint unique_login unique (login)
);
create table if not exists mpa
(
    mpa_id bigint generated by default as identity primary key,
    name   character varying(255),
    constraint unique_mpa unique (name)
);
create table if not exists films
(
    film_id      bigint generated by default as identity primary key,
    name         character varying(255),
    description  character varying(255),
    release_date date,
    duration     bigint,
    mpa_id       bigint references mpa(mpa_id) on delete restrict
);
create table if not exists genre
(
    genre_id bigint generated by default as identity primary key,
    genre    character varying(255)
);
create table if not exists genre_ref
(
    genre_ref_id bigint generated by default as identity primary key,
    genre_id     bigint references genre(genre_id) on delete cascade,
    film_id      bigint references films(film_id) on delete cascade,
    constraint unique_film_genre unique (film_id, genre_id)
);
create table if not exists user_friends
(
    user_friend_id bigint generated by default as identity primary key,
    user_id        bigint references users(user_id) on delete cascade,
    friend_id      bigint references users(user_id) on delete cascade,
    confirm        boolean,
    constraint unique_user_friend unique (user_id, friend_id)
);
create table if not exists film_likes
(
    film_like_id bigint generated by default as identity primary key,
    user_id      bigint references users(user_id) on delete cascade,
    film_id      bigint references films(film_id) on delete cascade,
    constraint unique_user_film_like unique (user_id, film_id)
);